name: DeployToS3
on:
  push:
    branches:
      - master
jobs:
  DeployCode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - run: |
          aws s3 sync . s3://dmscdc-files --acl public-read --exclude ".*"
